name: Check Conversations

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 10 minutes

jobs:
  check-conversations:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger conversation check
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "x-github-token: ${{ secrets.GITHUB_SECRET_TOKEN }}" \
          https://chicobot-eta.vercel.app/api/check-and-send-emails
